### PR TITLE
Converted to ES6. Moved to webpack build. Enabled Karma-based tests.

### PR DESCRIPTION
**Pull request by ifandelse**
@dcneiner @rniemeyer I still need to review this again to make sure I haven't missed anything obvious - but first...time to sleep.

### CODE REVIEW

**Comment by rniemeyer** [comment]
Pulled it down. Tests are passing, files look good, and example is working.  I don't see any obvious issues from the diff. Possibly want to mention the babel polyfill in docs (and maybe bower)?

**Comment by ifandelse** [comment]
@rniemeyer @dcneiner Good call - I'll include the README update in an amended commit hopefully later today.

**Comment by ifandelse** [comment]
@dcneiner @rniemeyer - README has been updated....

**Comment by rniemeyer** [comment]
@ifandelse - Merged, but didn't update version or tag, as I wasn't sure if you wanted to go to v0.5.0.

**Comment by ifandelse** [comment]
Thanks @rniemeyer - I tagged v0.5.0 and published to npm.

**Pull request merged**
